package Form;

import Form.dibuangsayang.IfMember;
import Form.laporan.ILapPembelian;
import Form.laporan.ILapPenjualan;
import Tool.CekIn;
import Tool.KoneksiDB;
import aksi.Login;
import com.mysql.jdbc.Statement;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class Frmenu extends javax.swing.JFrame implements Login {
    //membuat objek KoneksiDB dan variabel Connection
    KoneksiDB getCnn = new KoneksiDB();
    Connection _Cnn;
    
    //membuat variabel untuk menampung nilai
    String vid_user, vnama_user, vpass, vlev_user;
    String sqlselect;
    String lvUser, username;
    
    public Frmenu() {
        initComponents();
        disableMenu();
         Image image = new ImageIcon(getClass().getResource("/Image/settings-1.png")).getImage();
                setIconImage(image);
        this.setExtendedState(this.getExtendedState() | Frmenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JDesktopPane();
        panelLogin = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtIdUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbKeterangan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSistem = new javax.swing.JMenu();
        mnUser = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        mnMaster = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSupp = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        mnPenjualan = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnPembelian = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        mnLapPenjualan = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnLapPembelian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdUser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "ID. User :"));
        txtIdUser.setOpaque(false);
        txtIdUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUserActionPerformed(evt);
            }
        });

        txtPass.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Password"));
        txtPass.setOpaque(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/unlock_1.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shield.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN SISTEM KASIR");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-{ Sistem Informasi Kasir }-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdUser)
                            .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        panelLogin.addTab("Login User", new javax.swing.ImageIcon(getClass().getResource("/Image/Admin-Schoolar-Icon.png")), jPanel2); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        jLabel3.setText("Sistem Aplikasi Kasir");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Jln Raya Kesesi Kabupaten Pekalongan 51162");

        jpMenu.setLayer(panelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMenu.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMenu.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpMenu.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpMenuLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(33, 33, 33))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbKeterangan.setText("Nama User : .... | Lev. User : ...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbKeterangan)
                .addContainerGap())
        );

        mnSistem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/computer.png"))); // NOI18N
        mnSistem.setText("Sistem");

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/id-card_2.png"))); // NOI18N
        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        mnSistem.add(mnUser);

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/power_2.png"))); // NOI18N
        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnSistem.add(mnKeluar);

        jMenuBar1.add(mnSistem);

        mnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/store.png"))); // NOI18N
        mnMaster.setText("Master");

        mnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart-16_2.png"))); // NOI18N
        mnBarang.setText("Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        mnMaster.add(mnBarang);
        mnMaster.add(jSeparator1);

        mnSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart-16_2.png"))); // NOI18N
        mnSupp.setText("Supplier");
        mnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuppActionPerformed(evt);
            }
        });
        mnMaster.add(mnSupp);

        jMenuBar1.add(mnMaster);

        mnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/typewriter.png"))); // NOI18N
        mnTransaksi.setText("Transaksi");

        mnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart-12_2.png"))); // NOI18N
        mnPenjualan.setText("Penjualan");
        mnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPenjualanActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnPenjualan);
        mnTransaksi.add(jSeparator2);

        mnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cart_2.png"))); // NOI18N
        mnPembelian.setText("Pembelian");
        mnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPembelianActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnPembelian);

        jMenuBar1.add(mnTransaksi);

        mnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Menu/charts.png"))); // NOI18N
        mnLaporan.setText("Laporan");

        mnLapPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/statistics-3_2.png"))); // NOI18N
        mnLapPenjualan.setText("Laporan Penjualan");
        mnLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPenjualanActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapPenjualan);
        mnLaporan.add(jSeparator3);

        mnLapPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/statistics-3_2.png"))); // NOI18N
        mnLapPembelian.setText("Laporan Pembelian");
        mnLapPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPembelianActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapPembelian);

        jMenuBar1.add(mnLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        //mengambil nilai value dari txtIdUser dan membandingkannya dengan metode equals
       //jika text kosong jalankan if yang pertama
        if (txtIdUser.getText().equals("") || txtPass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan lengkapi data !", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
        //jalankan metode aksi login jika salah
            aksiLogin();
        }
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //mengambil nilai value dari txtIdUser dan membandingkannya dengan metode equals
       //jika text kosong jalankan if yang pertama
        if (txtIdUser.getText().equals("") || txtPass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan lengkapi data !", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
        //jalankan metode aksi login jika salah
            aksiLogin();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtIdUser.setText("");
        txtPass.setText("");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        //menampilkan menu didesktop pane
        //membuat objeck dari fromUser
        IfUser fr = new IfUser();
        //menambahkan fr di jpMenu(desktop pane)
        jpMenu.add(fr);
        //menampilkan frUser
        fr.setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
         //membuat metode opsi keluar
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah anda ingin keluar dari sistem?", "Informasi",
              JOptionPane.YES_NO_OPTION);
        //cek jika opsi yang dipilih YES jalankan sintack ini
        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        IfBarang1 fr = new IfBarang1();
        jpMenu.add(fr);        
        fr.setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuppActionPerformed
        IfSupp fr = new IfSupp();
        jpMenu.add(fr);        
        fr.setVisible(true);
    }//GEN-LAST:event_mnSuppActionPerformed

    private void mnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPenjualanActionPerformed
        try {
         IfPenjualan1 fr = new IfPenjualan1();
        jpMenu.add(fr);        
        fr.setVisible(true);   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error show "+e);
        }                
    }//GEN-LAST:event_mnPenjualanActionPerformed

    private void mnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPembelianActionPerformed
        IfPembelian1 fr = new IfPembelian1();
        jpMenu.add(fr);        
        fr.setVisible(true);
    }//GEN-LAST:event_mnPembelianActionPerformed

    private void mnLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPenjualanActionPerformed
        try {
        ILapPenjualan fr = new ILapPenjualan();
        jpMenu.add(fr);        
        fr.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error "+e);
        }
    }//GEN-LAST:event_mnLapPenjualanActionPerformed

    private void mnLapPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPembelianActionPerformed
         try {
        ILapPembelian fr = new ILapPembelian();
        jpMenu.add(fr);        
        fr.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error "+e);
        }
    }//GEN-LAST:event_mnLapPembelianActionPerformed

    private void txtIdUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUserActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) throws UnsupportedLookAndFeelException, IOException,
            ClassNotFoundException, InstantiationException, IllegalAccessException{
        try {
           com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Default", "Java Swing", "");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new Frmenu());
        } finally{
            new Frmenu().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JDesktopPane jpMenu;
    private javax.swing.JLabel lbKeterangan;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLapPembelian;
    private javax.swing.JMenuItem mnLapPenjualan;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenuItem mnPembelian;
    private javax.swing.JMenuItem mnPenjualan;
    private javax.swing.JMenu mnSistem;
    private javax.swing.JMenuItem mnSupp;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JTabbedPane panelLogin;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    @Override
    public void disableMenu() {
        mnSistem.setEnabled(false);
        mnMaster.setEnabled(false);
        mnTransaksi.setEnabled(false);
        mnLaporan.setEnabled(false);
//        mnAbout.setEnabled(false);
    }

    @Override
    public void enableMenu() {
        mnSistem.setEnabled(true);
        mnMaster.setEnabled(true);
        mnTransaksi.setEnabled(true);
        mnLaporan.setEnabled(true);
//        mnAbout.setEnabled(true);
    }
    private void noMenuAdmin(){
        mnPenjualan.setEnabled(false);
        mnLapPenjualan.setEnabled(false);
    }
    
    private void noMenuKasir(){
        mnUser.setEnabled(false);
//        mnBarang.setEnabled(false);
        mnSupp.setEnabled(false);
        mnPembelian.setEnabled(false);
        mnLapPembelian.setEnabled(false);
    }

    @Override
    public void aksiLogin() {
        int row = 0;
       //mengambil nilai value yang ada diTextField
        vid_user = txtIdUser.getText().replaceAll("'", "");
        vpass = txtPass.getText().replaceAll("'", "");
//        String lvUser;
        try {
            //kosongkan variabel _Cnn untuk menampung nilai dari koneksi
            _Cnn = null;
            _Cnn = getCnn.getConnection();            
            sqlselect = "select * from tbuser where iduser='"+vid_user+"' "
                    + "and pass='"+vpass+"' ";
            java.sql.Statement statement = _Cnn.createStatement();
            ResultSet resultSet = statement.executeQuery(sqlselect);
                        
                while (resultSet.next()) {                
                   row++;
                   if (row == 1) {
                        String var = resultSet.getString("lvuser");
                        username = resultSet.getString("user");
                        this.lvUser = var;                        
                            switch(var){
                                case "Administrator":
                                    enableMenu();                                    
                                    noMenuAdmin();
                                    CekIn.setLvuser("Administrator");
                                    //metode untuk menghilangkan panel login
                                    panelLogin.setVisible(false);
                                    lbKeterangan.setText("Nama User : "+username+" | Lev. User : "+lvUser);
                                break;
                                case "Kasir" :
//                                   JOptionPane.showMessageDialog(this, "Hello kasir");
                                    enableMenu();
                                    noMenuKasir();  
                                    CekIn.setLvuser("Kasir");
                                    panelLogin.setVisible(false);
                                    lbKeterangan.setText("Nama User : "+username+" | Lev. User : "+lvUser);
                                break;                                 
                            }                        
                    }
            }
             //cek jika tidak ada result/hasil
            if (!resultSet.first()) {
                JOptionPane.showMessageDialog(this, "ID. user dan Password salah", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error method aksiLOgin() : "+e);
        }
    }
}
